[bot]
token = "7057230300:AAGB9yqp5oi4tY8jAB2ZyW3DnC9WUyfk1cI"

owners = [1052986495]

[logs]
show_datetime = true

datetime_format = "%Y-%m-%d %H:%M:%S"


show_debug_logs = true

time_in_utc = false

renderer = "console"

use_colors_in_console = true